[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Run twice nightly during season (UTC)
[[scheduled.functions]]
  name = "update-wins"
  cron = "0 5,9 * * *"
